@host = localhost:4000/api
@contentType = application/json 

### AUTH Signup -> the token inspires in a day
POST http://{{host}}/auth/signup HTTP/1.1
User-Agent: rest-client
content-type: {{contentType}} 

{
    "username":"Senix",
    "email":"test@gmail.com",
    "password":"password"
}

### AUTH Signin -> the token inspires in a day
POST http://{{host}}/auth/signin HTTP/1.1
User-Agent: rest-client
content-type: {{contentType}} 

{
    "email":"senix@gmail.com",
    "password":"password"
}

### USER Profile -> the token inspires in a day
GET http://{{host}}/user/profile HTTP/1.1
User-Agent: rest-client
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA1YTBiZmU1ZjY1ZTM2Mjg5N2M1ZDgiLCJpYXQiOjE2Mjc4NTk4MjUsImV4cCI6MTYyNzk0NjIyNX0.pVhv67NEH2dtPaZxDMJSnHWPDdxog-dv0KRbvsduNzc 